/*
-- Query: SELECT * FROM s2757691db.a2_item
LIMIT 0, 1000

-- Date: 2013-02-03 20:24
*/
INSERT INTO `a2_Item` (`id`,`name`,`description`,`category_id`,`starting_price`,`manufacturer`,`expiration_date`,`seller_username_id`) VALUES (1,'iPod touch 5G','iPod touch, 5th generation, 64GB capacity, 24 hours continnuous music playback, running iOS6, with earpods',1,329.00,'Apple Inc.',NULL,1);
INSERT INTO `a2_Item` (`id`,`name`,`description`,`category_id`,`starting_price`,`manufacturer`,`expiration_date`,`seller_username_id`) VALUES (2,'iPhone 4','iPhone 4, 4th generation, 16GB capacity, 32 hours continuous music playback, running iOS5, CDMA+GSM (global) with earphones',3,649.00,'Apple Inc.',NULL,1);
INSERT INTO `a2_Item` (`id`,`name`,`description`,`category_id`,`starting_price`,`manufacturer`,`expiration_date`,`seller_username_id`) VALUES (3,'iPhone 5','iPhone 5, 6th generation, 32GB capacity, 32 hours continuous music playback, running iOS6, CDAM+GSM+LTE (global) with earpods',3,899.00,'Apple Inc.',NULL,1);
INSERT INTO `a2_Item` (`id`,`name`,`description`,`category_id`,`starting_price`,`manufacturer`,`expiration_date`,`seller_username_id`) VALUES (4,'iPad','iPad, 1st generation, A4 chip, 64GB capacity, Wifi only, running iOS 5.1',4,1024.00,'Apple Inc.',NULL,1);
INSERT INTO `a2_Item` (`id`,`name`,`description`,`category_id`,`starting_price`,`manufacturer`,`expiration_date`,`seller_username_id`) VALUES (5,'iPad 2','iPad 2, 2nd generation, A5 chip, 16GB capacity, Wifi + 3G, running iOS 6, front-facing Facetime camera, back-facing VGA camera',4,729.00,'Apple Inc.',NULL,1);
INSERT INTO `a2_Item` (`id`,`name`,`description`,`category_id`,`starting_price`,`manufacturer`,`expiration_date`,`seller_username_id`) VALUES (6,'iPad (3)','iPad with retina display, A5X chip, 3rd generation, 16GB capacity, Wifi only, running iOS 6, front-facing Facetime camera, back-facing 5MP camera with 1080p HD video recording',4,499.00,'Apple Inc.',NULL,1);
INSERT INTO `a2_Item` (`id`,`name`,`description`,`category_id`,`starting_price`,`manufacturer`,`expiration_date`,`seller_username_id`) VALUES (7,'iPad mini','iPad mini, 1st generation, A5 chip, 64GB capacity, Wifi only, running iOS 6, front-facing Facetime camera, back-facing 5MP camera with 1080p HD video recording',4,329.00,'Apple Inc.',NULL,1);
INSERT INTO `a2_Item` (`id`,`name`,`description`,`category_id`,`starting_price`,`manufacturer`,`expiration_date`,`seller_username_id`) VALUES (8,'iPad (4)','iPad with retina display, 4th generation, A6X chip, 16GB capacity, Wifi only, running iOS 6,  front-facing Facetime camera, back-facing 5MP camera with 1080p HD video recording',4,499.00,'Apple Inc.',NULL,1);
INSERT INTO `a2_Item` (`id`,`name`,`description`,`category_id`,`starting_price`,`manufacturer`,`expiration_date`,`seller_username_id`) VALUES (9,'Macbook 13" (late 2008)','Macbook aluminum unibody (late 2008), 2.0GHz Intel Core 2 Duo CPU, 2GB DD3 RAM, nVidia 9400M GPU, 160GB hard drive, Wifi+Bluetooth+Gigabit ethernet, DVD-RW superdrive, 2.04 kg weight',5,2048.00,'Apple Inc.',NULL,1);
INSERT INTO `a2_Item` (`id`,`name`,`description`,`category_id`,`starting_price`,`manufacturer`,`expiration_date`,`seller_username_id`) VALUES (10,'Macbook Air 11" (late 2011) ','Macbook Air 11" (late 2011), 1.6Ghz Intel Core i5 Dual Core CPU + Turboboost up to 2.6Ghz, 4GB DDR3 RAM, Intel HD 3000 graphics, 64GB flash drive, Wifi+Bluetooth+Display Port+Thunderbolt port+2 USB, 1.15 kg weight',5,1048.00,'Apple Inc.',NULL,1);
INSERT INTO `a2_Item` (`id`,`name`,`description`,`category_id`,`starting_price`,`manufacturer`,`expiration_date`,`seller_username_id`) VALUES (11,'Macbook Pro 15" (mid-2012) with retina display','Macbook Pro 15" (mid-2012) with retina display (2880 x 1440 pixels), 2.3GHz Intel Core i7 quad-core CPU, 4GB DDR3 RAM, Intel HD 4000 graphics, 500GB hard drive, Wifi+Bluetooth+Display Port+Thunderbolt port+2 USB+Gigabit ethernet, 2.02 kg weight',5,2999.00,'Apple Inc.',NULL,1);
INSERT INTO `a2_Item` (`id`,`name`,`description`,`category_id`,`starting_price`,`manufacturer`,`expiration_date`,`seller_username_id`) VALUES (12,'iMac 21.5" (late 2012)','iMac 21.5" 1920 x 1080 screen, 2.7GHz Intel Core i7 quad-core CPU, 8GB DDR3 RAM, nVidia GeForce GT 640M with 512MB dedicate GPU RAM, 1TB hard drive',6,1429.00,'Apple Inc.',NULL,1);
INSERT INTO `a2_Item` (`id`,`name`,`description`,`category_id`,`starting_price`,`manufacturer`,`expiration_date`,`seller_username_id`) VALUES (13,'iPad (5)','iPad with retina display, fifth generation',4,599.00,'Apple Inc.',NULL,1);
INSERT INTO `a2_Item` (`id`,`name`,`description`,`category_id`,`starting_price`,`manufacturer`,`expiration_date`,`seller_username_id`) VALUES (14,'Samsung Galaxy S3','4.8 inch screen, Android 4.0, sucks because it is not an Apple device',3,299.00,'Samsung Electronics',NULL,2);
INSERT INTO `a2_Item` (`id`,`name`,`description`,`category_id`,`starting_price`,`manufacturer`,`expiration_date`,`seller_username_id`) VALUES (15,'Samsung Galaxy S4','Oh and did you go out and do something special to celebrate? '''' ""',3,129.00,'Android-fanboy Electronics',NULL,2);
INSERT INTO `a2_Item` (`id`,`name`,`description`,`category_id`,`starting_price`,`manufacturer`,`expiration_date`,`seller_username_id`) VALUES (16,'Testing1','testing2',2,1.11,'Samsuck Electronics',NULL,2);
